"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-x!(0mq^!gy#isvf4!o)_%y^$830)1#*#yew5v1mf@a40h%o59z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
else:
    _hosts_env = os.environ.get("ALLOWED_HOSTS", "")
    if _hosts_env:
        ALLOWED_HOSTS = [h.strip() for h in _hosts_env.split(",") if h.strip()]
    else:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',       # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'hardle',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required by allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        ssl_require=False
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ==============================
# CORS / FRONTEND ACCESS (PROD)
# ==============================

CORS_ALLOW_CREDENTIALS = True


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "https://hardle-theta.vercel.app",
]

CORS_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "https://*.vercel.app",
    "https://*.railway.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "https://*.vercel.app",
    "https://*.railway.app",
]

# Allow Cross-Origin Cookies
# Set SECURE_COOKIES=True in production (HTTPS) environments
_SECURE_COOKIES = os.environ.get("SECURE_COOKIES", "False") == "True"

if _SECURE_COOKIES:
    # Prod: cross-origin (Vercel -> Railway) over HTTPS
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
else:
    # Dev: localhost over HTTP
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False

CSRF_COOKIE_HTTPONLY = False  # Frontend must read csrftoken cookie
SESSION_COOKIE_HTTPONLY = True  # Session cookie must never be accessible via JS
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# ALLAUTH / GOOGLE OAUTH
# ==============================

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',         # Standard email/password
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth (Google OAuth)
]

# After Google OAuth completes, redirect browser to SvelteKit frontend
_FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
LOGIN_REDIRECT_URL = f'{_FRONTEND_URL}/home'
ACCOUNT_LOGOUT_REDIRECT_URL = f'{_FRONTEND_URL}/login'

# Allauth account settings (allauth >= 65.x)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # email-only signup
ACCOUNT_LOGIN_METHODS = {'email'}  # Login via email
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip email confirmation for OAuth users

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
        # Auto-connect Google account to existing email accounts
        'SOCIALACCOUNT_AUTO_SIGNUP': True,
    }
}

# Ensure UserProfile is created for OAuth users via a signal (see models.py)
SOCIALACCOUNT_ADAPTER = 'hardle.adapters.HardleSocialAccountAdapter'


CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
]