# Generated by Django 6.0.2 on 2026-02-06 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_word', models.CharField(max_length=5)),
                ('guesses', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WIN', 'Win'), ('LOSE', 'Lose')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
