# Generated by Django 5.1.5 on 2026-02-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardle', '0002_gamesession_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(default='hard', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
