# Generated by Django 5.1.5 on 2026-02-21 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardle', '0004_pointsevent_userpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(default='daily', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'created_at'], name='hardle_game_user_id_f60174_idx'),
        ),
    ]
