# Generated by Django 5.1.5 on 2026-02-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardle', '0006_alter_pointsevent_id_alter_userpoints_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
